// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiCVvt51iAkYkmseaZBvAlZPFUb7SfmO4',
    appId: '1:506151123823:web:b32a1540d6db2eb0aa069a',
    messagingSenderId: '506151123823',
    projectId: 'dev-develop-qzrx64',
    authDomain: 'dev-develop-qzrx64.firebaseapp.com',
    storageBucket: 'dev-develop-qzrx64.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1Qi8IBG2gBEjThutQD3-4LHtoTJO-o1M',
    appId: '1:506151123823:android:331e9f0de27032dcaa069a',
    messagingSenderId: '506151123823',
    projectId: 'dev-develop-qzrx64',
    storageBucket: 'dev-develop-qzrx64.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFxSOlYUw71KAdPx89oPI5eaKO7fu1_w4',
    appId: '1:506151123823:ios:19e561b07ff9c2f0aa069a',
    messagingSenderId: '506151123823',
    projectId: 'dev-develop-qzrx64',
    storageBucket: 'dev-develop-qzrx64.appspot.com',
    iosBundleId: 'com.sportsperformance.user',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFxSOlYUw71KAdPx89oPI5eaKO7fu1_w4',
    appId: '1:506151123823:ios:19e561b07ff9c2f0aa069a',
    messagingSenderId: '506151123823',
    projectId: 'dev-develop-qzrx64',
    storageBucket: 'dev-develop-qzrx64.appspot.com',
    iosBundleId: 'com.sportsperformance.user',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCZ7USYlpIF5g224_LYJVVr5HrY-Z34p4',
    appId: '1:506151123823:web:327487099e90f1eeaa069a',
    messagingSenderId: '506151123823',
    projectId: 'dev-develop-qzrx64',
    authDomain: 'dev-develop-qzrx64.firebaseapp.com',
    storageBucket: 'dev-develop-qzrx64.appspot.com',
  );
}
